Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;

namespace CarDealership.Models
{
    public class Car : IValidatableObject
    {
        public int Id { get; set; }

        [Required]
        public string Make { get; set; }

        [Required]
        public string Model { get; set; }

        public string Year { get; set; }
        public string ImageUrl { get; set; }

        [Required]
        public string Title { get; set; }

        public string Description { get; set; }
        public decimal Price { get; set; }


        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> errors = new List<ValidationResult>();

            if (Year == null)
            {
                errors.Add(new ValidationResult("You must enter a year", new string[] { "Year" }));
            }

            return errors;
        }
    }
}

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Models/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarDealership.Models
{
    public class ContactForm : IValidatableObject
    {
        // Your task is to:
        //
        // Make all fields required
        // Ensure the Email field contains an '@' symbol
        // Ensure PhoneNumber is in the format: 1-XXX-XXX-XXXX
        // If the Income is less than 10000 and the PurchaseTimeFrameInMonts is greater than 12,
        // generate a model level area that says 'We don't want your business!'

        public string Name { get; set; }
        public int PurchaseTimeFrameInMonths { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public decimal? Income { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> errors = new List<ValidationResult>();

            if (Income == null)
            {
                errors.Add(new ValidationResult("Income must not be null", new string[] { "Income" }));
            }

            return errors;
        }
    }
}

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Controllers/CarController.cs
using CarDealership.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarDealership.Models;

namespace CarDealership.Controllers
{
    public class CarController : Controller
    {
        ICarRepository _repo = new DBCarRepository();

        // GET: Car
        public ActionResult Index()
        {
            var cars = _repo.GetAllCars();
            return View(cars);
        }

        public ActionResult Details(int id)
        {
            var car = _repo.GetCarById(id);
            return View(car);
        }

        public ActionResult AddACar()
        {
            return View();
        }

        public ActionResult EditCar(int id)
        {
            var car = _repo.GetCarById(id);
            return View(car);
        }

        public ActionResult ConfirmRemove(int id)
        {
            var car = _repo.GetCarById(id);
            return View(car);
        }

        public ActionResult RemoveCar(int id)
        {
            _repo.DeleteCar(id);
            return RedirectToAction("Index");          
        }

        [HttpPost]
        public ActionResult AddACar(Car car)
        {
            if (ModelState.IsValid)
            {
                _repo.AddCar(car);
                return RedirectToAction("Index");
            }
            else
            {
                return View("AddACar");
            }           
        }

        [HttpPost]
        public ActionResult EditCar(Car car)
        {
            if (ModelState.IsValid)
            {
                _repo.EditCar(car);
                return RedirectToAction("Index");
            }
            else
            {
                return View("EditCar");
            }
        }
    }
}

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Controllers/HomeController.cs
using CarDealership.Models;
using CarDealership.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact us using the form below!";

            return View();
        }

        [HttpPost]
        public ActionResult Sales(ContactForm contactForm)
        {
            ViewBag.Message = "Contact us using the form below!";

            if (ModelState.IsValid)
            {
                // yay, send a sales guy an email
                return RedirectToAction("Thanks");
            }
            else
            {
                return View("Contact");
            }
        }

        public ActionResult Thanks()
        {
            return View();
        }
    }
}

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Views/Car/AddACar.cshtml
@model CarDealership.Models.Car

@{
    ViewBag.Title = "AddACar";
}

<h2>Add A Car</h2>

@using (Html.BeginForm("AddACar", "Car", FormMethod.Post))
{
    <div>
        <div class="form-group">
            <label>Title</label><br />
            @Html.TextBoxFor(m => m.Title)
        </div>
        <div class="form-group">
            <label>Year</label><br/>
            @Html.TextBoxFor(m => m.Year)
        </div>
        <div class="form-group">
            <label>Make</label><br/>
            @Html.TextBoxFor(m => m.Make)
        </div>
        <div class="form-group">
            <label>Model</label><br/>
            @Html.TextBoxFor(m => m.Model)
        </div>
        <div class="form-group">
            <label>URL link to image</label><br/>
            @Html.TextBoxFor(m => m.ImageUrl)
        </div>
        <div class="form-group">
            <label>Price</label>
            @Html.TextBoxFor(m => m.Price)
        </div>
        <div class="form-group">
            <label>Add a description</label>
            @Html.TextBoxFor(m => m.Description)
        </div>
        <div>
            <button>Submit</button>
        </div>
    </div>
}

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Views/Car/ConfirmRemove.cshtml
@model CarDealership.Models.Car

@{
    ViewBag.Title = "ConfirmRemove";
}

<h2>ConfirmRemove</h2>
<div>
    Are you sure you want to delete the listing for the @Model.Year @Model.Make @Model.Model?
</div>
<div>
    <a href="@Url.Action("RemoveCar", new {id = Model.Id})">Yes</a>
</div>
<div>
    @Html.ActionLink("No", "Index")
</div>

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Views/Car/Details.cshtml
@model CarDealership.Models.Car
@{
    ViewBag.Title = "Details";
}
<h2>@Model.Title</h2>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="@Model.ImageUrl" alt="A car" class="car-image"/>
        </div>
        <div class="col-md-8">
            <div>
                @Model.Description
            </div>
            <h1>ONLY @string.Format("{0:C}", Model.Price)</h1>
            <div>
                <a href="@Url.Action("EditCar", new {id = Model.Id})">Edit this listing</a>
            </div>
            <div>
                <a href="@Url.Action("ConfirmRemove", new {id = Model.Id})">Remove this listing</a>
            </div>
        </div>
    </div>
</div>

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Views/Car/EditCar.cshtml
@model CarDealership.Models.Car

@{
    ViewBag.Title = "EditCar";
}

<h2>Edit Listing</h2>

@using (Html.BeginForm("EditCar", "Car", FormMethod.Post))
{
    <div>
        <div class="form-group">
            <label>Title</label><br />
            @Html.TextBoxFor(m => m.Title)
        </div>
        <div class="form-group">
            <label>Year</label><br />
            @Html.TextBoxFor(m => m.Year)
        </div>
        <div class="form-group">
            <label>Make</label><br />
            @Html.TextBoxFor(m => m.Make)
        </div>
        <div class="form-group">
            <label>Model</label><br />
            @Html.TextBoxFor(m => m.Model)
        </div>
        <div class="form-group">
            <label>URL link to image</label><br />
            @Html.TextBoxFor(m => m.ImageUrl)
        </div>
        <div class="form-group">
            <label>Price</label>
            @Html.TextBoxFor(m => m.Price)
        </div>
        <div class="form-group">
            <label>Add a description</label>
            @Html.TextBoxFor(m => m.Description)
        </div>
        <div>
            <button>Submit</button>
        </div>
    </div>
}

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Views/Car/Index.cshtml
@model IEnumerable<CarDealership.Models.Car>

@{
    ViewBag.Title = "Index";
}

<h2>Check out these fine, high-quality cars for sale! CLICK FOR DETAILS!</h2>

<div class="container">

    @for (int i = 0; i < Model.Count(); i = i + 3)
    {
        var ca = Model.ElementAt(i);
        <div class="row">
            <div class="col-md-4">
                <a href="@Url.Action("Details", new {id = ca.Id})">
                    <img src="@ca.ImageUrl" alt="This is a car for sale" class="car-image"/>
                </a>
            </div>
            @if ((i + 1) < Model.Count())
            {
                ca = Model.ElementAt(i + 1);
                <div class="col-md-4">
                    <a href="@Url.Action("Details", new {id = ca.Id})">
                        <img src="@ca.ImageUrl" alt="This is a car for sale" class="car-image"/>
                    </a>
                </div>
            }
            @if ((i + 2) < Model.Count())
            {
                ca = Model.ElementAt(i + 2);
                <div class="col-md-4">
                    <a href="@Url.Action("Details", new {id = ca.Id})">
                        <img src="@ca.ImageUrl" alt="This is a car for sale" class="car-image"/>
                    </a>
                </div>
            }
        </div>
        <div>&nbsp;
        </div>
    }
</div>
<div>
    @Html.ActionLink("Add a car", "AddACar")
</div>

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Views/Car/RemoveCar.cshtml
@model CarDealership.Models.Car

@{
    ViewBag.Title = "RemoveCar";
}

<h2>RemoveCar</h2>

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h1 style="font-size:144px;">WE'RE AMAZING</h1>

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Views/Home/Contact.cshtml
@model CarDealership.Models.ContactForm

@{
    ViewBag.Title = "Contact";
    var items = new List<SelectListItem>(){
      new SelectListItem() {
          Text = "6 months",
          Value = "6"
      },
            new SelectListItem() {
          Text = "12 months",
          Value = "12"
      },
            new SelectListItem() {
          Text = "24 months",
          Value = "24"
      },
            new SelectListItem() {
          Text = "36 months",
          Value = "36"
      }
    };
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

@using (Html.BeginForm("Sales", "Home", FormMethod.Post))
{
    <div>
        @Html.ValidationSummary(true)
    </div>
    <div>
        <div class="form-group">
            <label>Name</label><br />
            @Html.TextBoxFor(m => m.Name)
        </div>
        <div class="form-group">
            <label>Phone Number</label><br/>
            @Html.TextBoxFor(m => m.PhoneNumber)
        </div>
        <div class="form-group">
            <label>Time frame to purchase a new car</label><br />
            @Html.DropDownListFor(m => m.PurchaseTimeFrameInMonths, items)
        </div>
        <div class="form-group">
            <label>Email</label><br />
            @Html.TextBoxFor(m => m.Email)
        </div>
        <div class="form-group">
            <label>Income</label><br />
            @Html.TextBoxFor(m => m.Income)<br/>
            @Html.ValidationMessageFor(m => m.Income)<br />
        </div>
        <div>
            <button>Submit</button>
        </div>
    </div>
}

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome to the SWCG Car Dealership!</h1>
    <p>Go ahead and look around!</p>
</div>

Git/Labs/CarDealershipAddEditRemoveValidate/CarDealership/Views/Home/Thanks.cshtml
@{
    ViewBag.Title = "Thanks";
}

<h2>Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!</h2>